schedule:
  jobConfigs:
    mail:
      Config:
      updatequery: UPDATE public.eap_mail_sender SET processid = ?, isexecuted = ?, executeddate =? WHERE id = ?;
      updateinputs:
        processid: INTEGER
        isexecuted: BOOLEAN
        executeddate: TIMESTAMP
        id: INTEGER

    sms:
      Config:
      updatequery: UPDATE public.eap_sms_sender SET processid = ?, isexecuted = ?, executeddate =? WHERE id = ?;
      updateinputs:
        processid: INTEGER
        isexecuted: BOOLEAN
        executeddate: TIMESTAMP
        id: INTEGER